### ISSUE TITLE
Autocomplete not working in some cases

### ISSUE THREAD

**Issue by worm2fed** [Aidbox/viewdefinitions#184]
For example for this vd:
```yaml
resource: Patient
select:
  - column:
      - path: id
        name: id
        type: id
  - select:
      - column:
          - path: telecom.system
            name: tel_system
            type: code
          - name: gender
            path: gender
      - unionAll:
          - column:
              - path: name.family
                name: name
                type: string
          - forEach: name.given
            select:
              - column:
                  - path: $this
                    name: name
                    type: string
    forEach: contact
status: unknown
name: Big example
where: []
```

Try to edit `gender` path
