### ISSUE TITLE
Data table corrupted in some cases

### ISSUE THREAD

**Issue by worm2fed** [Aidbox/viewdefinitions#188]
> [!NOTE]
> It do not reproduces on import, only on manual creation

Here is a VD example
```yaml
status: unknown
name: Big example
resource: ExplanationOfBenefit
where:
  - path: use = 'claim'
  - path: status = 'active'
select:
  - column:
      - name: id
        path: id
      - name: status
        path: status
```

Which produces following result

![Image](https://github.com/Aidbox/viewdefinitions/assets/6579275/4822a5e7-2cf5-48e3-9cd0-12a019488c55)
